name: deploy

on:
  push:
    branches:
      - master
    paths-ignore: 
      - README.md

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0   

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.2'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:blog
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
